SHELL := /bin/bash
##
## -----:-----:-----:-----:-----:-----:-----:-----:
## Webproject

include ../usage/Makefile

##
## Target
.PHONY: webproject
webproject: ### TODO(86)
	cat .inittarget.web | $(SHELL) ###

##
## Note
### > TODO(86)

# Command variables
CAT := cat
